import { PolygonUtil } from "./polygon.util";
import { PolygonEventType } from "./enums";

export class PolygonInfo {
    polygon: ILatLng[][][] = [];
    trashcanPoint: ILatLng[] = [];
    sqmArea: number[] = [];
    perimeter: number[] = [];
    constructor(polygon) {
        console.log("PolygonInfo: ", polygon);
        polygon.forEach((polygons, i) => { this.trashcanPoint[i] = this.getTrashcanPoint(polygons[0]);
            this.sqmArea[i] = this.calculatePolygonArea(polygons[0]);
            this.perimeter[i] = this.calculatePolygonPerimeter(polygons[0]);
            console.log(polygons[0]);
            this.polygon[i] = polygons
        })
    }
    setSqmArea(area: number): void {
        this.sqmArea[0] = area;
    }
    private getTrashcanPoint(polygon: ILatLng[]): ILatLng {

        const res = Math.max.apply(Math, polygon.map(o => o.lat));
        const idx = polygon.findIndex(o => o.lat === res);

        let previousPoint: ILatLng;
        let nextPoint: ILatLng;

        if (idx > 0) {
            previousPoint = polygon[idx - 1];
            if (idx < polygon.length - 1) {
                nextPoint = polygon[idx + 1];
            } else {
                nextPoint = polygon[0];
            }
        } else {
            previousPoint = polygon[polygon.length - 1];
            nextPoint = polygon[idx + 1];
        }

        const secondPoint = (previousPoint.lng < nextPoint.lng) ? previousPoint : nextPoint;

        const midpoint = PolygonUtil.getMidPoint(polygon[idx], secondPoint);

        return midpoint;
    }
    private calculatePolygonArea(polygon: ILatLng[]): number {
        const area = PolygonUtil.getSqmArea((polygon) as any);
        return area;
    }
    private calculatePolygonPerimeter(polygon: ILatLng[]): number {
        const perimeter = PolygonUtil.getPerimeter((polygon) as any);
        return perimeter;
    }
    
}

export class PolygonDrawStates {
    isActivated: boolean;
    isFreeDrawMode: boolean;
    isMoveMode: boolean;
    canRevert: boolean;
    isAuto: boolean;
    hasPolygons: boolean;
    canUsePolyDraw: boolean;


    constructor() {
        this.canUsePolyDraw = false;
        this.reset();
    }

    activate(): void {
        this.reset();
        this.isActivated = true;
    }

    reset(): void {
        this.isActivated = false;
        this.hasPolygons = false;
        this.canRevert = false;
        this.isAuto = false;

        this.resetDrawModes();
    }

    resetDrawModes(): void {
        this.isFreeDrawMode = false;
        this.isMoveMode = false;
    }

    setFreeDrawMode(isAuto: boolean = false): void {
        if (isAuto) {
            this.isActivated = true;
        }
        if (this.isActivated) {
            this.resetDrawModes();
            this.isFreeDrawMode = true;
            if (isAuto) {
                this.isAuto = true;
            }
        }
    }

    setMoveMode(): void {
        if (this.isActivated) {
            this.resetDrawModes();
            this.isMoveMode = true;
        }
    }

    forceCanUseFreeDraw(): void {
        this.canUsePolyDraw = true;
    }
}
/**
 * @class
 * @public
 * @description Class that holds information about Polygon state
 * @property isAutoGenerated boolean - Polygon is autogenerated (or not)
 * @property polygon ILatLng[][][] - The polygon it self
 * @property polygonEventType PolygonEventType - Event type
 * @property drawStates PolygonDrawStates - draw states
 * @see PolygonEventType
 * @see PolygonDrawStates
 */
export class PolygonState {
    isAutoGenerated: boolean = false;
    polygon: ILatLng[][][] = [];
    polygonEventType: PolygonEventType;
    drawStates: PolygonDrawStates;
    constructor() {
        this.reset();
    }

    /**
     *
     * @param isAutoGenerated
     * @description Is the polygon auto generated or not
     */
    setIsAutoGenerated(isAutoGenerated: boolean): void {
        this.isAutoGenerated = isAutoGenerated;
    }

    /**
     *
     * @param polygon ILatLng[][][]
     * @description The polygon object it self
     * @see ILatLng
     */
    setPolygon(polygon: ILatLng[][][]): void {
        this.polygon = polygon;
    }

    /**
     * @description Resets all properties
     */
    reset(): void {
        this.isAutoGenerated = undefined;
        this.polygon = [];
        this.polygonEventType = undefined;
        this.drawStates = new PolygonDrawStates();
    }
}
export interface ILatLng {
    lat: number, 
    lng: number;
}